In [1]:
import numpy as np

In [2]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])


In [3]:
mean_a = np.array([np.mean(a[0:5,0:1]),np.mean(a[0:5,1:2])]) 
mean_a

array([2. , 8.4])

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [5]:
a=np.array(a_centered[0:5,0:1])

b=np.array(a_centered[0:5,1:2])


In [7]:
a_centered_sp = np.dot(a,b)

In [6]:
a = a.transpose()


In [8]:
a_centered_sp

array([[8.]])