In [1]:
import numpy as np

In [43]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])


In [44]:
mean_a = np.array([np.mean(a[0:5,0:1]),np.mean(a[0:5,1:2])]) 
mean_a

array([2. , 8.4])

In [45]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [46]:
a.shape == mean_a.shape

False

In [52]:
a=np.array(a_centered[0:5,0:1])
a
b=np.array(a_centered[0:5,1:2])
a

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [53]:
a = a.transpose()
a
b = b.transpose()


array([[-1.,  0.,  1.,  1., -1.]])

In [56]:
res=np.dot(a,b)

In [57]:
res

array([[8.]])